In [1]:
import numpy as np
import random

In [2]:
# Creating a bot that plays the 'Matrix Game' with a random strategy against the user

def run_game(myturn, n):
    placeholder_symbol = 5 # Defining the placeholder value
    matrix_size = (n, n)
    matrix = np.full(matrix_size, placeholder_symbol)
    rows = np.arange(1, n + 1)
    cols = np.arange(1, n + 1)
    coords = []
    for i in rows:
        for j in cols:
            coords.append([i, j])
    game(myturn, n, matrix, coords)

def game(myturn, n, matrix, coords):
    if myturn == 1:
        data = input('Your turn: In which entry would you like to put a zero (please enter the row and column with a space in between)?')
        i = int(data[0])
        j = int(data[2])
        matrix[i-1, j-1] = 0
        coords.remove([i, j])
        print('This is the current matrix \n', matrix)
        if len(coords) == 0:
            if np.linalg.det(matrix) == 0:
                print('You Win!')
                return
            else:
                print('You Lose!')
                return
        game(0, n, matrix, coords)
    else:
        rng = random.choice(coords)
        x = rng[0]
        y = rng[1]
        matrix[x-1, y-1] = 1
        coords.remove([x, y])
        print("Bot's turn: put a 1 in (", x, y, ")")
        print('This is the current matrix \n', matrix)
        if len(coords) == 0:
            if np.linalg.det(matrix) == 0:
                print('You Win!')
                return
            else:
                print('You Lose!')
                return
        game(1, n, matrix, coords)

# If turn=1 then we go first
# If turn=0 then the bot goes first
# Running the game for when we go first on a 3 x 3 matrix.
turn = 1
run_game(turn, 3)

Your turn: In which entry would you like to put a zero (please enter the row and column with a space in between)?2 2
This is the current matrix 
 [[5 5 5]
 [5 0 5]
 [5 5 5]]
Bot's turn: put a 1 in ( 3 3 )
This is the current matrix 
 [[5 5 5]
 [5 0 5]
 [5 5 1]]
Your turn: In which entry would you like to put a zero (please enter the row and column with a space in between)?2 1
This is the current matrix 
 [[5 5 5]
 [0 0 5]
 [5 5 1]]
Bot's turn: put a 1 in ( 1 2 )
This is the current matrix 
 [[5 1 5]
 [0 0 5]
 [5 5 1]]
Your turn: In which entry would you like to put a zero (please enter the row and column with a space in between)?2 3
This is the current matrix 
 [[5 1 5]
 [0 0 0]
 [5 5 1]]
Bot's turn: put a 1 in ( 1 1 )
This is the current matrix 
 [[1 1 5]
 [0 0 0]
 [5 5 1]]
Your turn: In which entry would you like to put a zero (please enter the row and column with a space in between)?1 3
This is the current matrix 
 [[1 1 0]
 [0 0 0]
 [5 5 1]]
Bot's turn: put a 1 in ( 3 1 )
This is t